/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.trade.hosting.risk.manager.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EHostingRiskItemValueType implements org.apache.thrift.TEnum {
  DOUBLE_VALUE(1),
  PERCENT_VALUE(2),
  LONG_VALUE(3);

  private final int value;

  private EHostingRiskItemValueType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EHostingRiskItemValueType findByValue(int value) { 
    switch (value) {
      case 1:
        return DOUBLE_VALUE;
      case 2:
        return PERCENT_VALUE;
      case 3:
        return LONG_VALUE;
      default:
        return null;
    }
  }
}
