package xueqiao.trade.hosting.dealing.core.dfa;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.soldier.base.logger.AppLog;

import com.google.common.base.Preconditions;

import xueqiao.trade.hosting.HostingExecOrderStateValue;
import static xueqiao.trade.hosting.HostingExecOrderStateValue.*;
import static xueqiao.trade.hosting.dealing.core.dfa.TransferCode.*;

public class Graph {
    public static Graph INSTANCE = new Graph();
    
    private List<Arc> arcList = new ArrayList<Arc>();
    private Map<HostingExecOrderStateValue, Map<TransferCode, HostingExecOrderStateValue>> 
            arcMapping = new HashMap<HostingExecOrderStateValue, Map<TransferCode, HostingExecOrderStateValue>>();
    
    private Graph() {
        addArc(ORDER_WAITING_SLED_SEND, SLED_SYSTEM_REJECT_SEND, ORDER_SLED_SEND_FAILED);
        addArc(ORDER_WAITING_SLED_SEND, SLED_CALL_ALLOCREF_SUCCESS, ORDER_SLED_ALLOC_REF_FINISHED);
        addArc(ORDER_WAITING_SLED_SEND, SLED_CALL_ALLOCREF_FAILED, ORDER_SLED_SEND_FAILED);
        
        addArc(ORDER_SLED_ALLOC_REF_FINISHED, SLED_CALL_ORDERINSERT_FAILED_SELF_MATCH, ORDER_SLED_SEND_FAILED);
        addArc(ORDER_SLED_ALLOC_REF_FINISHED, SLED_CALL_ORDERINSERT_FAILED_CONTRACT_ERROR, ORDER_SLED_SEND_FAILED);

        // 非明确意义的错误，要到UNKOWN状态绕一圈
        addArc(ORDER_SLED_ALLOC_REF_FINISHED, SLED_CALL_ORDERINSERT_FAILED_CONNECT, ORDER_SLED_SEND_UNKOWN);
        addArc(ORDER_SLED_ALLOC_REF_FINISHED, SLED_CALL_ORDERINSERT_FAILED_OTHER, ORDER_SLED_SEND_UNKOWN);
        addArc(ORDER_SLED_ALLOC_REF_FINISHED, SLED_CALL_ORDERINSERT_FAILED_ORDERREF_EXPIRED, ORDER_SLED_SEND_UNKOWN);
        addArc(ORDER_SLED_ALLOC_REF_FINISHED, SLED_CALL_ORDERINSERT_UNKOWN, ORDER_SLED_SEND_UNKOWN);
        addArc(ORDER_SLED_ALLOC_REF_FINISHED, SLED_CALL_ORDERINSERT_SUCCESS, ORDER_SLED_SEND_UNKOWN);
        
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_ORDER_NOTFOUND_EVENT, ORDER_SLED_SEND_FAILED);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_ORDER_REJECT_EVENT, ORDER_UPSIDE_REJECTED);
        addArc(ORDER_SLED_SEND_UNKOWN, SLED_ORDERINSERT_FAILED_CALLBACK, ORDER_UPSIDE_REJECTED);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_UPSIDE_RECEIVED_EVENT, ORDER_UPSIDE_RECEIVED);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_ORDER_RESTING_EVENT, ORDER_UPSIDE_RESTING);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_CONDITION_NOT_TRIGGERED_EVENT, ORDER_CONDITION_NOT_TRIGGER);
        addArc(ORDER_SLED_SEND_UNKOWN, RECEIVED_CONDITION_TRIGGERED_EVENT, ORDER_CONDITION_TRIGGEDED);
        
//        addArc(ORDER_UPSIDE_RECEIVED, RECEIVED_UPSIDE_RECEIVED_EVENT, ORDER_UPSIDE_RECEIVED);
        addArc(ORDER_UPSIDE_RECEIVED, RECEIVED_ORDER_REJECT_EVENT, ORDER_UPSIDE_REJECTED);
        addArc(ORDER_UPSIDE_RECEIVED, RECEIVED_ORDER_RESTING_EVENT, ORDER_UPSIDE_RESTING);
        addArc(ORDER_UPSIDE_RECEIVED, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED);
        addArc(ORDER_UPSIDE_RECEIVED, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_RECEIVED, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        
//        addArc(ORDER_UPSIDE_RESTING, RECEIVED_ORDER_RESTING_EVENT, ORDER_UPSIDE_RESTING);
        addArc(ORDER_UPSIDE_RESTING, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED);
        addArc(ORDER_UPSIDE_RESTING, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_RESTING, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        
        addArc(ORDER_UPSIDE_PARTFINISHED, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED);
        addArc(ORDER_UPSIDE_PARTFINISHED, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        
        addArc(ORDER_CONDITION_NOT_TRIGGER, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_CONDITION_NOT_TRIGGER, RECEIVED_CONDITION_TRIGGERED_EVENT, ORDER_CONDITION_TRIGGEDED);
        
//        addArc(ORDER_UPSIDE_FINISHED, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
//        addArc(ORDER_UPSIDE_DELETED, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, RECEIVED_ORDER_RESTING_EVENT, ORDER_UPSIDE_RESTING_WAITING_REVOKE);
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_RESTING_WAITING_REVOKE);
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, SLED_CALL_ORDERDELETE_FAILED, ORDER_UPSIDE_RECEIVED);
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, SLED_CALL_ORDERDELETE_SUCCESS, ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, SLED_CALL_ORDERDELETE_UNKOWN, ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_RECEIVED_WAITING_REVOKE, RECEIVED_ORDER_CANCEL_RECEIVED_EVENT, ORDER_UPSIDE_REVOKE_RECEIVED);
        
        addArc(ORDER_UPSIDE_RESTING_WAITING_REVOKE, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE);
        addArc(ORDER_UPSIDE_RESTING_WAITING_REVOKE, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_RESTING_WAITING_REVOKE, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_UPSIDE_RESTING_WAITING_REVOKE, SLED_CALL_ORDERDELETE_FAILED, ORDER_UPSIDE_RESTING);
        addArc(ORDER_UPSIDE_RESTING_WAITING_REVOKE, SLED_CALL_ORDERDELETE_SUCCESS, ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_RESTING_WAITING_REVOKE, SLED_CALL_ORDERDELETE_UNKOWN, ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_RESTING_WAITING_REVOKE, RECEIVED_ORDER_CANCEL_RECEIVED_EVENT, ORDER_UPSIDE_REVOKE_RECEIVED);
        
        addArc(ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE);
        addArc(ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE, SLED_CALL_ORDERDELETE_FAILED, ORDER_UPSIDE_PARTFINISHED);
        addArc(ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE, SLED_CALL_ORDERDELETE_SUCCESS, ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE, SLED_CALL_ORDERDELETE_UNKOWN, ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_PARTFINISHED_WAITING_REVOKE, RECEIVED_ORDER_CANCEL_RECEIVED_EVENT, ORDER_UPSIDE_REVOKE_RECEIVED);
        
        addArc(ORDER_CONDITION_NOT_TRIGGER_WAITING_REVOKE, RECEIVED_CONDITION_TRIGGERED_EVENT, ORDER_CONDITION_TRIGGEDED);
        addArc(ORDER_CONDITION_NOT_TRIGGER_WAITING_REVOKE, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_CONDITION_NOT_TRIGGER_WAITING_REVOKE, SLED_CALL_ORDERDELETE_FAILED, ORDER_CONDITION_NOT_TRIGGER);
        addArc(ORDER_CONDITION_NOT_TRIGGER_WAITING_REVOKE, SLED_CALL_ORDERDELETE_SUCCESS, ORDER_CONDITION_NOT_TRIGGER_REVOKE_SEND_UNKOWN);
        addArc(ORDER_CONDITION_NOT_TRIGGER_WAITING_REVOKE, SLED_CALL_ORDERDELETE_UNKOWN, ORDER_CONDITION_NOT_TRIGGER_REVOKE_SEND_UNKOWN);
        addArc(ORDER_CONDITION_NOT_TRIGGER_WAITING_REVOKE, RECEIVED_ORDER_CANCEL_RECEIVED_EVENT, ORDER_UPSIDE_REVOKE_RECEIVED);
        
        addArc(ORDER_CONDITION_NOT_TRIGGER_REVOKE_SEND_UNKOWN, SLED_ORDERDELETE_FAILED_CALLBACK, ORDER_CONDITION_NOT_TRIGGER);
        addArc(ORDER_CONDITION_NOT_TRIGGER_REVOKE_SEND_UNKOWN, SLED_REVOKE_TIMEOUT, ORDER_CONDITION_NOT_TRIGGER);
        
        addArc(ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_RESTING_EVENT, ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_CANCEL_RECEIVED_EVENT, ORDER_UPSIDE_REVOKE_RECEIVED);
        addArc(ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN, SLED_ORDERDELETE_FAILED_CALLBACK, ORDER_UPSIDE_RECEIVED);
        addArc(ORDER_UPSIDE_RECEIVED_REVOKE_SEND_UNKOWN, SLED_REVOKE_TIMEOUT, ORDER_UPSIDE_RECEIVED);
        
        addArc(ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_CANCEL_RECEIVED_EVENT, ORDER_UPSIDE_REVOKE_RECEIVED);
        addArc(ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN, SLED_ORDERDELETE_FAILED_CALLBACK, ORDER_UPSIDE_RESTING);
        addArc(ORDER_UPSIDE_RESTING_REVOKE_SEND_UNKOWN, SLED_REVOKE_TIMEOUT, ORDER_UPSIDE_RESTING);
        
        addArc(ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN);
        addArc(ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        addArc(ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN, RECEIVED_ORDER_CANCEL_RECEIVED_EVENT, ORDER_UPSIDE_REVOKE_RECEIVED);
        addArc(ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN, SLED_ORDERDELETE_FAILED_CALLBACK, ORDER_UPSIDE_PARTFINISHED);
        addArc(ORDER_UPSIDE_PARTFINISHED_REVOKE_SEND_UNKOWN, SLED_REVOKE_TIMEOUT, ORDER_UPSIDE_PARTFINISHED);
        
        addArc(ORDER_UPSIDE_REVOKE_RECEIVED, RECEIVED_ORDER_RESTING_EVENT, ORDER_UPSIDE_RESTING);
        addArc(ORDER_UPSIDE_REVOKE_RECEIVED, RECEIVED_ORDER_PARTFINISHED_EVENT, ORDER_UPSIDE_PARTFINISHED);
        addArc(ORDER_UPSIDE_REVOKE_RECEIVED, RECEIVED_ORDER_FINISHED_EVENT, ORDER_UPSIDE_FINISHED);
        addArc(ORDER_UPSIDE_REVOKE_RECEIVED, RECEIVED_ORDER_CANCELLED_EVENT, ORDER_UPSIDE_DELETED);
        
        addArc(ORDER_UPSIDE_REJECTED, SLED_MODIFY_RETRY, ORDER_WAITING_SLED_SEND);
    }

    public void addArc(HostingExecOrderStateValue fromState
            , TransferCode transferCode
            , HostingExecOrderStateValue toState) {
        addArc(new Arc(fromState, transferCode, toState));
    }
    
    private void addArc(Arc arc) {
        Preconditions.checkNotNull(arc);
        
        Map<TransferCode, HostingExecOrderStateValue> transferCodeMapping = arcMapping.get(arc.getFromState());
        if (transferCodeMapping == null) {
            transferCodeMapping = new HashMap<TransferCode, HostingExecOrderStateValue>();
            arcMapping.put(arc.getFromState(), transferCodeMapping); 
        }
        
        if (transferCodeMapping.containsKey(arc.getTransferCode())) {
            AppLog.f("duplicate arc for " + arc);
            return ;
        }
        
        transferCodeMapping.put(arc.getTransferCode(), arc.getToState());
        arcList.add(arc);
    }
    
    public HostingExecOrderStateValue getNextState(HostingExecOrderStateValue fromState, TransferCode transferCode) {
        Map<TransferCode, HostingExecOrderStateValue> transferCodeMapping = arcMapping.get(fromState);
        if (transferCodeMapping == null) {
            return null;
        }
        return transferCodeMapping.get(transferCode);
    }
    
    public void dump(OutputStream stream) throws IOException {
        for (Arc arc : arcList) {
            stream.write(arc.toString().getBytes(Charset.forName("UTF-8")));
        }
    }
}
