/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.trade.hosting.position.fee.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CommissionInfo implements org.apache.thrift.TBase<CommissionInfo, CommissionInfo._Fields>, java.io.Serializable, Cloneable, Comparable<CommissionInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CommissionInfo");

  private static final org.apache.thrift.protocol.TField OPEN_RATIO_BY_MONEY_FIELD_DESC = new org.apache.thrift.protocol.TField("openRatioByMoney", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField OPEN_RATIO_BY_VOLUME_FIELD_DESC = new org.apache.thrift.protocol.TField("openRatioByVolume", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField CLOSE_RATIO_BY_MONEY_FIELD_DESC = new org.apache.thrift.protocol.TField("closeRatioByMoney", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField CLOSE_RATIO_BY_VOLUME_FIELD_DESC = new org.apache.thrift.protocol.TField("closeRatioByVolume", org.apache.thrift.protocol.TType.DOUBLE, (short)4);
  private static final org.apache.thrift.protocol.TField CLOSE_TODAY_RATIO_BY_MONEY_FIELD_DESC = new org.apache.thrift.protocol.TField("closeTodayRatioByMoney", org.apache.thrift.protocol.TType.DOUBLE, (short)5);
  private static final org.apache.thrift.protocol.TField CLOSE_TODAY_RATIO_BY_VOLUME_FIELD_DESC = new org.apache.thrift.protocol.TField("closeTodayRatioByVolume", org.apache.thrift.protocol.TType.DOUBLE, (short)6);
  private static final org.apache.thrift.protocol.TField CURRENCY_FIELD_DESC = new org.apache.thrift.protocol.TField("currency", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField CURRENCY_GROUP_FIELD_DESC = new org.apache.thrift.protocol.TField("currencyGroup", org.apache.thrift.protocol.TType.STRING, (short)8);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CommissionInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CommissionInfoTupleSchemeFactory());
  }

  public double openRatioByMoney; // optional
  public double openRatioByVolume; // optional
  public double closeRatioByMoney; // optional
  public double closeRatioByVolume; // optional
  public double closeTodayRatioByMoney; // optional
  public double closeTodayRatioByVolume; // optional
  public String currency; // optional
  public String currencyGroup; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPEN_RATIO_BY_MONEY((short)1, "openRatioByMoney"),
    OPEN_RATIO_BY_VOLUME((short)2, "openRatioByVolume"),
    CLOSE_RATIO_BY_MONEY((short)3, "closeRatioByMoney"),
    CLOSE_RATIO_BY_VOLUME((short)4, "closeRatioByVolume"),
    CLOSE_TODAY_RATIO_BY_MONEY((short)5, "closeTodayRatioByMoney"),
    CLOSE_TODAY_RATIO_BY_VOLUME((short)6, "closeTodayRatioByVolume"),
    CURRENCY((short)7, "currency"),
    CURRENCY_GROUP((short)8, "currencyGroup");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPEN_RATIO_BY_MONEY
          return OPEN_RATIO_BY_MONEY;
        case 2: // OPEN_RATIO_BY_VOLUME
          return OPEN_RATIO_BY_VOLUME;
        case 3: // CLOSE_RATIO_BY_MONEY
          return CLOSE_RATIO_BY_MONEY;
        case 4: // CLOSE_RATIO_BY_VOLUME
          return CLOSE_RATIO_BY_VOLUME;
        case 5: // CLOSE_TODAY_RATIO_BY_MONEY
          return CLOSE_TODAY_RATIO_BY_MONEY;
        case 6: // CLOSE_TODAY_RATIO_BY_VOLUME
          return CLOSE_TODAY_RATIO_BY_VOLUME;
        case 7: // CURRENCY
          return CURRENCY;
        case 8: // CURRENCY_GROUP
          return CURRENCY_GROUP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OPENRATIOBYMONEY_ISSET_ID = 0;
  private static final int __OPENRATIOBYVOLUME_ISSET_ID = 1;
  private static final int __CLOSERATIOBYMONEY_ISSET_ID = 2;
  private static final int __CLOSERATIOBYVOLUME_ISSET_ID = 3;
  private static final int __CLOSETODAYRATIOBYMONEY_ISSET_ID = 4;
  private static final int __CLOSETODAYRATIOBYVOLUME_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.OPEN_RATIO_BY_MONEY,_Fields.OPEN_RATIO_BY_VOLUME,_Fields.CLOSE_RATIO_BY_MONEY,_Fields.CLOSE_RATIO_BY_VOLUME,_Fields.CLOSE_TODAY_RATIO_BY_MONEY,_Fields.CLOSE_TODAY_RATIO_BY_VOLUME,_Fields.CURRENCY,_Fields.CURRENCY_GROUP};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPEN_RATIO_BY_MONEY, new org.apache.thrift.meta_data.FieldMetaData("openRatioByMoney", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.OPEN_RATIO_BY_VOLUME, new org.apache.thrift.meta_data.FieldMetaData("openRatioByVolume", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CLOSE_RATIO_BY_MONEY, new org.apache.thrift.meta_data.FieldMetaData("closeRatioByMoney", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CLOSE_RATIO_BY_VOLUME, new org.apache.thrift.meta_data.FieldMetaData("closeRatioByVolume", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CLOSE_TODAY_RATIO_BY_MONEY, new org.apache.thrift.meta_data.FieldMetaData("closeTodayRatioByMoney", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CLOSE_TODAY_RATIO_BY_VOLUME, new org.apache.thrift.meta_data.FieldMetaData("closeTodayRatioByVolume", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CURRENCY, new org.apache.thrift.meta_data.FieldMetaData("currency", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CURRENCY_GROUP, new org.apache.thrift.meta_data.FieldMetaData("currencyGroup", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CommissionInfo.class, metaDataMap);
  }

  public CommissionInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CommissionInfo(CommissionInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.openRatioByMoney = other.openRatioByMoney;
    this.openRatioByVolume = other.openRatioByVolume;
    this.closeRatioByMoney = other.closeRatioByMoney;
    this.closeRatioByVolume = other.closeRatioByVolume;
    this.closeTodayRatioByMoney = other.closeTodayRatioByMoney;
    this.closeTodayRatioByVolume = other.closeTodayRatioByVolume;
    if (other.isSetCurrency()) {
      this.currency = other.currency;
    }
    if (other.isSetCurrencyGroup()) {
      this.currencyGroup = other.currencyGroup;
    }
  }

  public CommissionInfo deepCopy() {
    return new CommissionInfo(this);
  }

  @Override
  public void clear() {
    setOpenRatioByMoneyIsSet(false);
    this.openRatioByMoney = 0.0;
    setOpenRatioByVolumeIsSet(false);
    this.openRatioByVolume = 0.0;
    setCloseRatioByMoneyIsSet(false);
    this.closeRatioByMoney = 0.0;
    setCloseRatioByVolumeIsSet(false);
    this.closeRatioByVolume = 0.0;
    setCloseTodayRatioByMoneyIsSet(false);
    this.closeTodayRatioByMoney = 0.0;
    setCloseTodayRatioByVolumeIsSet(false);
    this.closeTodayRatioByVolume = 0.0;
    this.currency = null;
    this.currencyGroup = null;
  }

  public double getOpenRatioByMoney() {
    return this.openRatioByMoney;
  }

  public CommissionInfo setOpenRatioByMoney(double openRatioByMoney) {
    this.openRatioByMoney = openRatioByMoney;
    setOpenRatioByMoneyIsSet(true);
    return this;
  }

  public void unsetOpenRatioByMoney() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPENRATIOBYMONEY_ISSET_ID);
  }

  /** Returns true if field openRatioByMoney is set (has been assigned a value) and false otherwise */
  public boolean isSetOpenRatioByMoney() {
    return EncodingUtils.testBit(__isset_bitfield, __OPENRATIOBYMONEY_ISSET_ID);
  }

  public void setOpenRatioByMoneyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPENRATIOBYMONEY_ISSET_ID, value);
  }

  public double getOpenRatioByVolume() {
    return this.openRatioByVolume;
  }

  public CommissionInfo setOpenRatioByVolume(double openRatioByVolume) {
    this.openRatioByVolume = openRatioByVolume;
    setOpenRatioByVolumeIsSet(true);
    return this;
  }

  public void unsetOpenRatioByVolume() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPENRATIOBYVOLUME_ISSET_ID);
  }

  /** Returns true if field openRatioByVolume is set (has been assigned a value) and false otherwise */
  public boolean isSetOpenRatioByVolume() {
    return EncodingUtils.testBit(__isset_bitfield, __OPENRATIOBYVOLUME_ISSET_ID);
  }

  public void setOpenRatioByVolumeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPENRATIOBYVOLUME_ISSET_ID, value);
  }

  public double getCloseRatioByMoney() {
    return this.closeRatioByMoney;
  }

  public CommissionInfo setCloseRatioByMoney(double closeRatioByMoney) {
    this.closeRatioByMoney = closeRatioByMoney;
    setCloseRatioByMoneyIsSet(true);
    return this;
  }

  public void unsetCloseRatioByMoney() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CLOSERATIOBYMONEY_ISSET_ID);
  }

  /** Returns true if field closeRatioByMoney is set (has been assigned a value) and false otherwise */
  public boolean isSetCloseRatioByMoney() {
    return EncodingUtils.testBit(__isset_bitfield, __CLOSERATIOBYMONEY_ISSET_ID);
  }

  public void setCloseRatioByMoneyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CLOSERATIOBYMONEY_ISSET_ID, value);
  }

  public double getCloseRatioByVolume() {
    return this.closeRatioByVolume;
  }

  public CommissionInfo setCloseRatioByVolume(double closeRatioByVolume) {
    this.closeRatioByVolume = closeRatioByVolume;
    setCloseRatioByVolumeIsSet(true);
    return this;
  }

  public void unsetCloseRatioByVolume() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CLOSERATIOBYVOLUME_ISSET_ID);
  }

  /** Returns true if field closeRatioByVolume is set (has been assigned a value) and false otherwise */
  public boolean isSetCloseRatioByVolume() {
    return EncodingUtils.testBit(__isset_bitfield, __CLOSERATIOBYVOLUME_ISSET_ID);
  }

  public void setCloseRatioByVolumeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CLOSERATIOBYVOLUME_ISSET_ID, value);
  }

  public double getCloseTodayRatioByMoney() {
    return this.closeTodayRatioByMoney;
  }

  public CommissionInfo setCloseTodayRatioByMoney(double closeTodayRatioByMoney) {
    this.closeTodayRatioByMoney = closeTodayRatioByMoney;
    setCloseTodayRatioByMoneyIsSet(true);
    return this;
  }

  public void unsetCloseTodayRatioByMoney() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CLOSETODAYRATIOBYMONEY_ISSET_ID);
  }

  /** Returns true if field closeTodayRatioByMoney is set (has been assigned a value) and false otherwise */
  public boolean isSetCloseTodayRatioByMoney() {
    return EncodingUtils.testBit(__isset_bitfield, __CLOSETODAYRATIOBYMONEY_ISSET_ID);
  }

  public void setCloseTodayRatioByMoneyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CLOSETODAYRATIOBYMONEY_ISSET_ID, value);
  }

  public double getCloseTodayRatioByVolume() {
    return this.closeTodayRatioByVolume;
  }

  public CommissionInfo setCloseTodayRatioByVolume(double closeTodayRatioByVolume) {
    this.closeTodayRatioByVolume = closeTodayRatioByVolume;
    setCloseTodayRatioByVolumeIsSet(true);
    return this;
  }

  public void unsetCloseTodayRatioByVolume() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CLOSETODAYRATIOBYVOLUME_ISSET_ID);
  }

  /** Returns true if field closeTodayRatioByVolume is set (has been assigned a value) and false otherwise */
  public boolean isSetCloseTodayRatioByVolume() {
    return EncodingUtils.testBit(__isset_bitfield, __CLOSETODAYRATIOBYVOLUME_ISSET_ID);
  }

  public void setCloseTodayRatioByVolumeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CLOSETODAYRATIOBYVOLUME_ISSET_ID, value);
  }

  public String getCurrency() {
    return this.currency;
  }

  public CommissionInfo setCurrency(String currency) {
    this.currency = currency;
    return this;
  }

  public void unsetCurrency() {
    this.currency = null;
  }

  /** Returns true if field currency is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrency() {
    return this.currency != null;
  }

  public void setCurrencyIsSet(boolean value) {
    if (!value) {
      this.currency = null;
    }
  }

  public String getCurrencyGroup() {
    return this.currencyGroup;
  }

  public CommissionInfo setCurrencyGroup(String currencyGroup) {
    this.currencyGroup = currencyGroup;
    return this;
  }

  public void unsetCurrencyGroup() {
    this.currencyGroup = null;
  }

  /** Returns true if field currencyGroup is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrencyGroup() {
    return this.currencyGroup != null;
  }

  public void setCurrencyGroupIsSet(boolean value) {
    if (!value) {
      this.currencyGroup = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case OPEN_RATIO_BY_MONEY:
      if (value == null) {
        unsetOpenRatioByMoney();
      } else {
        setOpenRatioByMoney((Double)value);
      }
      break;

    case OPEN_RATIO_BY_VOLUME:
      if (value == null) {
        unsetOpenRatioByVolume();
      } else {
        setOpenRatioByVolume((Double)value);
      }
      break;

    case CLOSE_RATIO_BY_MONEY:
      if (value == null) {
        unsetCloseRatioByMoney();
      } else {
        setCloseRatioByMoney((Double)value);
      }
      break;

    case CLOSE_RATIO_BY_VOLUME:
      if (value == null) {
        unsetCloseRatioByVolume();
      } else {
        setCloseRatioByVolume((Double)value);
      }
      break;

    case CLOSE_TODAY_RATIO_BY_MONEY:
      if (value == null) {
        unsetCloseTodayRatioByMoney();
      } else {
        setCloseTodayRatioByMoney((Double)value);
      }
      break;

    case CLOSE_TODAY_RATIO_BY_VOLUME:
      if (value == null) {
        unsetCloseTodayRatioByVolume();
      } else {
        setCloseTodayRatioByVolume((Double)value);
      }
      break;

    case CURRENCY:
      if (value == null) {
        unsetCurrency();
      } else {
        setCurrency((String)value);
      }
      break;

    case CURRENCY_GROUP:
      if (value == null) {
        unsetCurrencyGroup();
      } else {
        setCurrencyGroup((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case OPEN_RATIO_BY_MONEY:
      return Double.valueOf(getOpenRatioByMoney());

    case OPEN_RATIO_BY_VOLUME:
      return Double.valueOf(getOpenRatioByVolume());

    case CLOSE_RATIO_BY_MONEY:
      return Double.valueOf(getCloseRatioByMoney());

    case CLOSE_RATIO_BY_VOLUME:
      return Double.valueOf(getCloseRatioByVolume());

    case CLOSE_TODAY_RATIO_BY_MONEY:
      return Double.valueOf(getCloseTodayRatioByMoney());

    case CLOSE_TODAY_RATIO_BY_VOLUME:
      return Double.valueOf(getCloseTodayRatioByVolume());

    case CURRENCY:
      return getCurrency();

    case CURRENCY_GROUP:
      return getCurrencyGroup();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case OPEN_RATIO_BY_MONEY:
      return isSetOpenRatioByMoney();
    case OPEN_RATIO_BY_VOLUME:
      return isSetOpenRatioByVolume();
    case CLOSE_RATIO_BY_MONEY:
      return isSetCloseRatioByMoney();
    case CLOSE_RATIO_BY_VOLUME:
      return isSetCloseRatioByVolume();
    case CLOSE_TODAY_RATIO_BY_MONEY:
      return isSetCloseTodayRatioByMoney();
    case CLOSE_TODAY_RATIO_BY_VOLUME:
      return isSetCloseTodayRatioByVolume();
    case CURRENCY:
      return isSetCurrency();
    case CURRENCY_GROUP:
      return isSetCurrencyGroup();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CommissionInfo)
      return this.equals((CommissionInfo)that);
    return false;
  }

  public boolean equals(CommissionInfo that) {
    if (that == null)
      return false;

    boolean this_present_openRatioByMoney = true && this.isSetOpenRatioByMoney();
    boolean that_present_openRatioByMoney = true && that.isSetOpenRatioByMoney();
    if (this_present_openRatioByMoney || that_present_openRatioByMoney) {
      if (!(this_present_openRatioByMoney && that_present_openRatioByMoney))
        return false;
      if (this.openRatioByMoney != that.openRatioByMoney)
        return false;
    }

    boolean this_present_openRatioByVolume = true && this.isSetOpenRatioByVolume();
    boolean that_present_openRatioByVolume = true && that.isSetOpenRatioByVolume();
    if (this_present_openRatioByVolume || that_present_openRatioByVolume) {
      if (!(this_present_openRatioByVolume && that_present_openRatioByVolume))
        return false;
      if (this.openRatioByVolume != that.openRatioByVolume)
        return false;
    }

    boolean this_present_closeRatioByMoney = true && this.isSetCloseRatioByMoney();
    boolean that_present_closeRatioByMoney = true && that.isSetCloseRatioByMoney();
    if (this_present_closeRatioByMoney || that_present_closeRatioByMoney) {
      if (!(this_present_closeRatioByMoney && that_present_closeRatioByMoney))
        return false;
      if (this.closeRatioByMoney != that.closeRatioByMoney)
        return false;
    }

    boolean this_present_closeRatioByVolume = true && this.isSetCloseRatioByVolume();
    boolean that_present_closeRatioByVolume = true && that.isSetCloseRatioByVolume();
    if (this_present_closeRatioByVolume || that_present_closeRatioByVolume) {
      if (!(this_present_closeRatioByVolume && that_present_closeRatioByVolume))
        return false;
      if (this.closeRatioByVolume != that.closeRatioByVolume)
        return false;
    }

    boolean this_present_closeTodayRatioByMoney = true && this.isSetCloseTodayRatioByMoney();
    boolean that_present_closeTodayRatioByMoney = true && that.isSetCloseTodayRatioByMoney();
    if (this_present_closeTodayRatioByMoney || that_present_closeTodayRatioByMoney) {
      if (!(this_present_closeTodayRatioByMoney && that_present_closeTodayRatioByMoney))
        return false;
      if (this.closeTodayRatioByMoney != that.closeTodayRatioByMoney)
        return false;
    }

    boolean this_present_closeTodayRatioByVolume = true && this.isSetCloseTodayRatioByVolume();
    boolean that_present_closeTodayRatioByVolume = true && that.isSetCloseTodayRatioByVolume();
    if (this_present_closeTodayRatioByVolume || that_present_closeTodayRatioByVolume) {
      if (!(this_present_closeTodayRatioByVolume && that_present_closeTodayRatioByVolume))
        return false;
      if (this.closeTodayRatioByVolume != that.closeTodayRatioByVolume)
        return false;
    }

    boolean this_present_currency = true && this.isSetCurrency();
    boolean that_present_currency = true && that.isSetCurrency();
    if (this_present_currency || that_present_currency) {
      if (!(this_present_currency && that_present_currency))
        return false;
      if (!this.currency.equals(that.currency))
        return false;
    }

    boolean this_present_currencyGroup = true && this.isSetCurrencyGroup();
    boolean that_present_currencyGroup = true && that.isSetCurrencyGroup();
    if (this_present_currencyGroup || that_present_currencyGroup) {
      if (!(this_present_currencyGroup && that_present_currencyGroup))
        return false;
      if (!this.currencyGroup.equals(that.currencyGroup))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CommissionInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOpenRatioByMoney()).compareTo(other.isSetOpenRatioByMoney());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpenRatioByMoney()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.openRatioByMoney, other.openRatioByMoney);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOpenRatioByVolume()).compareTo(other.isSetOpenRatioByVolume());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpenRatioByVolume()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.openRatioByVolume, other.openRatioByVolume);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCloseRatioByMoney()).compareTo(other.isSetCloseRatioByMoney());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCloseRatioByMoney()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.closeRatioByMoney, other.closeRatioByMoney);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCloseRatioByVolume()).compareTo(other.isSetCloseRatioByVolume());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCloseRatioByVolume()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.closeRatioByVolume, other.closeRatioByVolume);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCloseTodayRatioByMoney()).compareTo(other.isSetCloseTodayRatioByMoney());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCloseTodayRatioByMoney()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.closeTodayRatioByMoney, other.closeTodayRatioByMoney);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCloseTodayRatioByVolume()).compareTo(other.isSetCloseTodayRatioByVolume());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCloseTodayRatioByVolume()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.closeTodayRatioByVolume, other.closeTodayRatioByVolume);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCurrency()).compareTo(other.isSetCurrency());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrency()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.currency, other.currency);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCurrencyGroup()).compareTo(other.isSetCurrencyGroup());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrencyGroup()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.currencyGroup, other.currencyGroup);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CommissionInfo(");
    boolean first = true;

    if (isSetOpenRatioByMoney()) {
      sb.append("openRatioByMoney:");
      sb.append(this.openRatioByMoney);
      first = false;
    }
    if (isSetOpenRatioByVolume()) {
      if (!first) sb.append(", ");
      sb.append("openRatioByVolume:");
      sb.append(this.openRatioByVolume);
      first = false;
    }
    if (isSetCloseRatioByMoney()) {
      if (!first) sb.append(", ");
      sb.append("closeRatioByMoney:");
      sb.append(this.closeRatioByMoney);
      first = false;
    }
    if (isSetCloseRatioByVolume()) {
      if (!first) sb.append(", ");
      sb.append("closeRatioByVolume:");
      sb.append(this.closeRatioByVolume);
      first = false;
    }
    if (isSetCloseTodayRatioByMoney()) {
      if (!first) sb.append(", ");
      sb.append("closeTodayRatioByMoney:");
      sb.append(this.closeTodayRatioByMoney);
      first = false;
    }
    if (isSetCloseTodayRatioByVolume()) {
      if (!first) sb.append(", ");
      sb.append("closeTodayRatioByVolume:");
      sb.append(this.closeTodayRatioByVolume);
      first = false;
    }
    if (isSetCurrency()) {
      if (!first) sb.append(", ");
      sb.append("currency:");
      if (this.currency == null) {
        sb.append("null");
      } else {
        sb.append(this.currency);
      }
      first = false;
    }
    if (isSetCurrencyGroup()) {
      if (!first) sb.append(", ");
      sb.append("currencyGroup:");
      if (this.currencyGroup == null) {
        sb.append("null");
      } else {
        sb.append(this.currencyGroup);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CommissionInfoStandardSchemeFactory implements SchemeFactory {
    public CommissionInfoStandardScheme getScheme() {
      return new CommissionInfoStandardScheme();
    }
  }

  private static class CommissionInfoStandardScheme extends StandardScheme<CommissionInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CommissionInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPEN_RATIO_BY_MONEY
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.openRatioByMoney = iprot.readDouble();
              struct.setOpenRatioByMoneyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OPEN_RATIO_BY_VOLUME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.openRatioByVolume = iprot.readDouble();
              struct.setOpenRatioByVolumeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CLOSE_RATIO_BY_MONEY
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.closeRatioByMoney = iprot.readDouble();
              struct.setCloseRatioByMoneyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CLOSE_RATIO_BY_VOLUME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.closeRatioByVolume = iprot.readDouble();
              struct.setCloseRatioByVolumeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CLOSE_TODAY_RATIO_BY_MONEY
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.closeTodayRatioByMoney = iprot.readDouble();
              struct.setCloseTodayRatioByMoneyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // CLOSE_TODAY_RATIO_BY_VOLUME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.closeTodayRatioByVolume = iprot.readDouble();
              struct.setCloseTodayRatioByVolumeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CURRENCY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.currency = iprot.readString();
              struct.setCurrencyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // CURRENCY_GROUP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.currencyGroup = iprot.readString();
              struct.setCurrencyGroupIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CommissionInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetOpenRatioByMoney()) {
        oprot.writeFieldBegin(OPEN_RATIO_BY_MONEY_FIELD_DESC);
        oprot.writeDouble(struct.openRatioByMoney);
        oprot.writeFieldEnd();
      }
      if (struct.isSetOpenRatioByVolume()) {
        oprot.writeFieldBegin(OPEN_RATIO_BY_VOLUME_FIELD_DESC);
        oprot.writeDouble(struct.openRatioByVolume);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCloseRatioByMoney()) {
        oprot.writeFieldBegin(CLOSE_RATIO_BY_MONEY_FIELD_DESC);
        oprot.writeDouble(struct.closeRatioByMoney);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCloseRatioByVolume()) {
        oprot.writeFieldBegin(CLOSE_RATIO_BY_VOLUME_FIELD_DESC);
        oprot.writeDouble(struct.closeRatioByVolume);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCloseTodayRatioByMoney()) {
        oprot.writeFieldBegin(CLOSE_TODAY_RATIO_BY_MONEY_FIELD_DESC);
        oprot.writeDouble(struct.closeTodayRatioByMoney);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCloseTodayRatioByVolume()) {
        oprot.writeFieldBegin(CLOSE_TODAY_RATIO_BY_VOLUME_FIELD_DESC);
        oprot.writeDouble(struct.closeTodayRatioByVolume);
        oprot.writeFieldEnd();
      }
      if (struct.currency != null) {
        if (struct.isSetCurrency()) {
          oprot.writeFieldBegin(CURRENCY_FIELD_DESC);
          oprot.writeString(struct.currency);
          oprot.writeFieldEnd();
        }
      }
      if (struct.currencyGroup != null) {
        if (struct.isSetCurrencyGroup()) {
          oprot.writeFieldBegin(CURRENCY_GROUP_FIELD_DESC);
          oprot.writeString(struct.currencyGroup);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CommissionInfoTupleSchemeFactory implements SchemeFactory {
    public CommissionInfoTupleScheme getScheme() {
      return new CommissionInfoTupleScheme();
    }
  }

  private static class CommissionInfoTupleScheme extends TupleScheme<CommissionInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CommissionInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetOpenRatioByMoney()) {
        optionals.set(0);
      }
      if (struct.isSetOpenRatioByVolume()) {
        optionals.set(1);
      }
      if (struct.isSetCloseRatioByMoney()) {
        optionals.set(2);
      }
      if (struct.isSetCloseRatioByVolume()) {
        optionals.set(3);
      }
      if (struct.isSetCloseTodayRatioByMoney()) {
        optionals.set(4);
      }
      if (struct.isSetCloseTodayRatioByVolume()) {
        optionals.set(5);
      }
      if (struct.isSetCurrency()) {
        optionals.set(6);
      }
      if (struct.isSetCurrencyGroup()) {
        optionals.set(7);
      }
      oprot.writeBitSet(optionals, 8);
      if (struct.isSetOpenRatioByMoney()) {
        oprot.writeDouble(struct.openRatioByMoney);
      }
      if (struct.isSetOpenRatioByVolume()) {
        oprot.writeDouble(struct.openRatioByVolume);
      }
      if (struct.isSetCloseRatioByMoney()) {
        oprot.writeDouble(struct.closeRatioByMoney);
      }
      if (struct.isSetCloseRatioByVolume()) {
        oprot.writeDouble(struct.closeRatioByVolume);
      }
      if (struct.isSetCloseTodayRatioByMoney()) {
        oprot.writeDouble(struct.closeTodayRatioByMoney);
      }
      if (struct.isSetCloseTodayRatioByVolume()) {
        oprot.writeDouble(struct.closeTodayRatioByVolume);
      }
      if (struct.isSetCurrency()) {
        oprot.writeString(struct.currency);
      }
      if (struct.isSetCurrencyGroup()) {
        oprot.writeString(struct.currencyGroup);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CommissionInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(8);
      if (incoming.get(0)) {
        struct.openRatioByMoney = iprot.readDouble();
        struct.setOpenRatioByMoneyIsSet(true);
      }
      if (incoming.get(1)) {
        struct.openRatioByVolume = iprot.readDouble();
        struct.setOpenRatioByVolumeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.closeRatioByMoney = iprot.readDouble();
        struct.setCloseRatioByMoneyIsSet(true);
      }
      if (incoming.get(3)) {
        struct.closeRatioByVolume = iprot.readDouble();
        struct.setCloseRatioByVolumeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.closeTodayRatioByMoney = iprot.readDouble();
        struct.setCloseTodayRatioByMoneyIsSet(true);
      }
      if (incoming.get(5)) {
        struct.closeTodayRatioByVolume = iprot.readDouble();
        struct.setCloseTodayRatioByVolumeIsSet(true);
      }
      if (incoming.get(6)) {
        struct.currency = iprot.readString();
        struct.setCurrencyIsSet(true);
      }
      if (incoming.get(7)) {
        struct.currencyGroup = iprot.readString();
        struct.setCurrencyGroupIsSet(true);
      }
    }
  }

}

