cc_library(
    name = 'trade_hosting_framework',
    srcs = [
        'src/hosting_message_graph.cpp',
        'src/hosting_message_sender.cpp',
    ],
    export_incs = [
        'src',
    ],
    deps = [
        '//cpp_platform/message_bus:message_bus_api',
    ]
)