/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.goose.errorcode;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SmsErrorCode implements org.apache.thrift.TEnum {
  SEND_VERIFY_CODE_FAILED(80201),
  SEND_VERIFY_CODE_TOO_FREQUENTLY(80202),
  SEND_VERIFY_CODE_TOO_MANY_TIMES_ONE_DAY(80203),
  VERIFY_CODE_ERROR(80222),
  SEND_SMS_FAILED(80230);

  private final int value;

  private SmsErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SmsErrorCode findByValue(int value) { 
    switch (value) {
      case 80201:
        return SEND_VERIFY_CODE_FAILED;
      case 80202:
        return SEND_VERIFY_CODE_TOO_FREQUENTLY;
      case 80203:
        return SEND_VERIFY_CODE_TOO_MANY_TIMES_ONE_DAY;
      case 80222:
        return VERIFY_CODE_ERROR;
      case 80230:
        return SEND_SMS_FAILED;
      default:
        return null;
    }
  }
}
