/*
 * es9_error_mapping.cpp
 *
 *  Created on: 2018年4月14日
 *      Author: 44385
 */


#include "es9_error_mapping.h"

#include <boost/lexical_cast.hpp>
#include <map>

#include "iTapAPIError.h"


using namespace ITapTrade;

namespace es9ext {
namespace framework {

static std::map<ITapTrade::TAPIINT32, std::string> MAPPING = {
        {TAPIERROR_LOGIN, "登录过程执行错误"},
        {TAPIERROR_LOGIN_USER, "登录用户不存在"},
        {TAPIERROR_LOGIN_DDA, "需要进行动态认证"},
        {TAPIERROR_LOGIN_LICENSE, "登录用户未授权"},
        {TAPIERROR_LOGIN_MODULE, "登录模块不正确"},
        {TAPIERROR_LOGIN_FORCE, "需要强制修改密码"},
        {TAPIERROR_LOGIN_STATE, "登录状态禁止登陆"},
        {TAPIERROR_LOGIN_PASS, "登录密码不正确"},
        {TAPIERROR_LOGIN_RIGHT, "没有该模块登录权限"},
        {TAPIERROR_LOGIN_COUNT, "登录数量超限"},
        {TAPIERROR_LOGIN_NOTIN_SERVERFLAGUSRES, "登录用户不在服务器标识下可登录用户列表中"},
        {TAPIERROR_LOGIN_FREEZE, "登录用户已被冻结"},
        {TAPIERROR_LOGIN_TOFREEZE, "密码错误，用户冻结"},
        {TAPIERROR_LOGIN_ACCOUNTSTATE, " 客户状态不允许登录"},
        {TAPIERROR_LOGIN_SECCERTIFI, "需要进行二次认证"},
        {TAPIERROR_SECONDCERTIFICATION_FAIL, "二次验证失败"},
        {TAPIERROR_SECONDCERTIFICATION_TIMEOVER, "二次验证超时"},
        {TAPIERROR_CONN_DATABASE, "上手内部错误,数据库连接失败"},
        {TAPIERROR_OPER_DATABASE, "上手内部错误,数据库操作失败"},
        {TAPIERROR_NEED_ONETOONE, "不允许一对多"},
        {TAPIERROR_EXIST_RELATEINFO, "存在关联信息"},
        {TAPIERROR_EXIST_RELATEINFOOFGROUP, "分组有下属或在操作员下属中"},
        {TAPIERROR_USERPASSWORD_MOD_SOURCE, "登录用户密码修改失败,原始密码错误"},
        {TAPIERROR_USERPASSWORD_MOD_SAME, "登录用户密码修改失败,不能与前n次密码相同"},
        {TAPIERROR_USERPASSWORD_MOD_COMPLEXITY, "登录用户密码修改失败,新密码不符合密码复杂度要求"},
        {TAPIERROR_CURRENCY_ONLY_ONEBASE, "一个币种组只能设置一个基币"},
        {TAPIERROR_CURRENCY_ONLY_USDHKD, "基币只能是美元或港币"},
        {TAPIERROR_ORDERINSERT_ACCOUNT, "资金账号不存在"},
        {TAPIERROR_ORDERINSERT_ACCOUNT_STATE, "资金账号状态不正确"},
        {TAPIERROR_ORDERINSERT_CONTRACT, "下单无效的合约"},
        {TAPIERROR_ORDERINSERT_LME_NOTREADY, "LME未准备就绪"},
        {TAPIERROR_ORDER_NOTRADE_ACCOUNT, "客户权限禁止交易"},
        {TAPIERROR_ORDER_NOTRADE_COM_GROUP, "客户品种分组禁止交易"},
        {TAPIERROR_ORDER_NOTRADE_ACC_CONTRACT, "客户合约特设禁止交易"},
        {TAPIERROR_ORDER_NOTRADE_SYSTEM, "系统权限禁止交易"},
        {TAPIERROR_ORDER_CLOSE_ACCOUNT, "客户权限只可平仓"},
        {TAPIERROR_ORDER_CLOSE_ACC_CONTRACT, "客户合约特设只可平仓"},
        {TAPIERROR_ORDER_CLOSE_SYSTEM, "系统权限只可平仓"},
        {TAPIERROR_ORDER_CLOSE_DAYS, "提前天数限制只可平仓"},
        {TAPIERROR_ORDER_NOTRADE_RISK, "客户品种风控权限禁止交易"},
        {TAPIERROR_ORDER_CLOSE_RISK, "客户品种风控权限只可平仓"},
        {TAPIERROR_ORDERINSERT_POSITIONMAX, "持仓量超过最大限制"},
        {TAPIERROR_ORDERINSERT_ONCEMAX, "下单超过单笔最大量"},
        {TAPIERROR_ORDERINSERT_TRADEROUTE, "上手内部下单合约无交易路由"},
        {TAPIERROR_UPPERCHANNEL_NOT_LOGIN, "未登录网关"},
        {TAPIERROR_ORDERINSERT_NOTENOUGHFUND, "下单资金不足"},
        {TAPIERROR_ORDERINSERT_FEE, "手续费参数错误"},
        {TAPIERROR_ORDERINSERT_MARGIN, "保证金参数错误"},
        {TAPIERROR_ORDERINSERT_BASENOFUND, "总基币资金不足"},
        {TAPIERROR_ORDERINSERT_MARGINAMOUNT, "超过保证金额度"},
        {TAPIERROR_ORDERINSERT_OPENRATIO, "总基币超过开仓比例限制"},
        {TAPIERROR_ORDERINSERT_GROUP_OPENRATIO, "独立币种组超过开仓比例限制"},
        {TAPIERROR_ORDERINSERT_RISKARRAY, "风险阵列参数错误"},
        {TAPIERROR_ORDERDELETE_NOT_SYSNO, "撤单无此系统号"},
        {TAPIERROR_ORDERDELETE_NOT_STATE, "此状态不允许撤单"},
        {TAPIERROR_ORDERDELETE_NO_INPUT, "录单不允许撤单"},
        {TAPIERROR_ORDERMODIFY_NOT_STATE, "此状态不允许改单"},
        {TAPIERROR_ORDERMODIFY_BACK_INPUT, "人工单不允许改单"},
        {TAPIERROR_ORDERMODIFY_RISK_ORDER, " 风险报单不允许改单"},
        {TAPIERROR_ORDERMODIFY_ERROR_QTY, "成交量大于改单量"},
        {TAPIERROR_ORDERINPUT_CANNOTMOVE, "已删除报单不能转移"},
        {TAPIERROR_ORDERINPUT_REPEAT, "录单重复"},
        {TAPIERROR_CONTRACT_QUOTE, "合约行情价格修改失败"},
        {TAPIERROR_UPPER_ONCEMAX, "下单超过上手单笔最大量"},
        {TAPIERROR_UPPER_POSITIONMAX, "下单超过上手最大持仓量"},
        {TAPIERROR_ORDERINSERT_CLOSEMODE, "开平方式错误"},
        {TAPIERROR_CLOSE_ORDER, "委托平仓持仓不足"},
        {TAPIERROR_CLOSE_MATCH, "成交平仓失败"},
        {TAPIERROR_MOD_DEL_NO_ORDER, "未找到本地委托"},
        {TAPIERROR_MOD_DEL_GATEWAY_DISCON, "与网关断开连接"},
        {TAPIERROR_MATCHINPUT_REPEAT, "录单成交重复"},
        {TAPIERROR_MATCHINPUT_NO_ORDER, "录单成交未找到对应委托"},
        {TAPIERROR_MATCHINPUT_NO_CONTRACT, "录单成交合约不存在"},
        {TAPIERROR_MATCHINPUT_PARM_ERROR, "录单成交参数错误"},
        {TAPIERROR_MATCHINPUT_OSTATE_ERROR, "录单成交委托状态错误"},
        {TAPIERROR_MATCHREMOVE_NO_MATCH, "成交删除未找到成交"},
        {TAPIERROR_MATCHREMOVE_STATE_ERROR, "此状态成交不可删"},
        {TAPIERROR_ORDERINPUT_STATE_ERROR, "不允许录入此状态订单"},
        {TAPIERROR_ORDERINPUT_MOD_ERROR, "错误的修改订单请求"},
        {TAPIERROR_ORDERREMOVE_ERROR, "订单不可删，存在对应成交"},
        {TAPIERROR_ORDERINPUT_MOD_STATE_ERROR, "不合法的委托状态"},
        {TAPIERROR_ORDEREXCHANGE_STATE_ERROR, "此状态不允许订单转移"},
        {TAPIERROR_ORDERMARKET_DELETE_NOTFOUND, "做市商双边撤单未找到委托"},
        {TAPIERROR_ORDERMARKET_DEL_ACCOUNT_NE, "做市商双边撤单客户不一致"},
        {TAPIERROR_ORDERMARKET_DEL_COMMODITY_NE, "做市商双边撤单品种不一致"},
        {TAPIERROR_ORDERMARKET_DEL_CONTRACT_NE, "做市商双边撤单合约不一致"},
        {TAPIERROR_ORDERMARKET_DEL_SIDE_EQ, "做市商双边撤单买卖方向相同"},
        {TAPIERROR_ORDERMARKET_DEL_SIDE_ERROR, "做市商双边撤单买卖方向错误"},
        {TAPIERROR_GW_NOT_READY, "网关未就绪，未连接上手"},
        {TAPIERROR_GW_INVALID_COMMODITY, "网关品种错误"},
        {TAPIERROR_GW_INVALID_CONTRACT, "网关合约错误"},
        {TAPIERROR_GW_INVALID_FIELD, "网关报单字段有误"},
        {TAPIERROR_GW_INVALID_PRICE, "网关价格不合法"},
        {TAPIERROR_GW_INVALID_VOLUME, "网关数量不合法"},
        {TAPIERROR_GW_INVALID_TYPE, "网关报单类型不合法"},
        {TAPIERROR_GW_INVALID_MODE, "网关委托模式不合法"},
        {TAPIERROR_GW_ORDER_NOT_EXIST, "网关委托不存在"},
        {TAPIERROR_GW_SEND_FAIL, "网关发送报单失败"},
        {TAPIERROR_GW_REJ_BYUPPER, "网关被上手拒绝"},
        {TAPIERROR_TRADEFRONT_MODULETYPEERR, "前置不允许该模块登录"},
        {TAPIERROR_TRADEFRONT_TOOMANYDATA, "前置一次请求太多数据"},
        {TAPIERROR_TRADEFRONT_NODATA, "前置没有所要数据"},
        {TAPIERROR_TRADEFRONT_DISCONNECT_TRADE, "前置与交易断开"},
        {TAPIERROR_TRADEFRONT_DISCONNECT_MANAGE, "前置与管理断开"},
        {TAPIERROR_TRADEFRONT_ACCOUNT, "下属资金账号不存在"},
        {TAPIERROR_TRADEFRONT_ORDER, "该操作员不允许交易"},
        {TAPIERROR_TRADEFRONT_FREQUENCY, "查询频率过快"},
        {TAPIERROR_TRADEFRONT_RUFUSE, "该授权不予许登录"},
        {TAPIERROR_SUCCEED, "成功"},
        {TAPIERROR_ConnectFail, "连接服务失败"},
        {TAPIERROR_LinkAuthFail, "链路认证失败"},
        {TAPIERROR_HostUnavailable, "主机地址不可用"},
        {TAPIERROR_SendDataError, "发送数据错误"},
        {TAPIERROR_TestIDError, "测试编号不合法"},
        {TAPIERROR_NotReadyTestNetwork, "没准备好测试网络"},
        {TAPIERROR_CurTestNotOver, "当前网络测试还没结束"},
        {TAPIERROR_NOFrontAvailable, "没用可用的接入前置"},
        {TAPIERROR_DataPathAvaiable, "数据路径不可用"},
        {TAPIERROR_RepeatLogin, "重复登录"},
        {TAPIERROR_InnerError, "上手内部错误"},
        {TAPIERROR_LastReqNotFinish, "上一次请求还没有结束"},
        {TAPIERROR_InputValueError, "输入参数非法"},
        {TAPIERROR_AuthCode_Invalid, "授权码不合法"},
        {TAPIERROR_AuthCode_Expired, "授权码超期"},
        {TAPIERROR_AuthCode_TypeNotMatch, "授权码类型不匹配"},
        {TAPIERROR_API_NotReady, "API还没有准备好"},
        {TAPIERROR_UDP_LISTEN_FAILED, "UDP端口监听失败"},
        {TAPIERROR_UDP_LISTENING, "UDP正在监听"},
        {TAPIERROR_NotImplemented, "接口未实现"},
        {TAPIERROR_CallOneTimeOnly, "每次登陆只允许调用一次"},
        {TAPIERROR_ORDER_FREQUENCY, "超过下单频率"},
        {TAPIERROR_RENTQRY_TOOFAST, "查询频率太快"},
        {TAPIERROR_CALL_NOCONDITION, "不符合调用条件"},
        {TAPIERROR_ORDER_NOTFOUND, "改单撤单时没有找到对应订单"},
        {TAPIERROR_LOGPATH_EMPTY, "日志路径为空"},
        {TAPIERROR_LOGPATH_FAILOPEN, "打开日志文件失败"},
        {TAPIERROR_RIGHT_TRADER, "没有交易员登录权限"},
        {TAPIERROR_RIGHT_ORDERINPUT, "没有订单录入或者成交录入"},
        {TAPIERROR_RIGHT_LOCALOPERATION, "没有订单修改和订单删除权限，成交删除权限"},
        {TAPIERROR_RIGHT_ORDERTRANSFER, "没有订单转移权限"},
        {TAPIERROR_FILLINPUT_SYSTEMNO, "成交录入时系统号为空"},
        {TAPIERROR_FILLREMOVE_MATCHNO, "成交删除时成交号为空"},
        {TAPIERROR_FILLREQMOVE_NOFUND, "成交删除时没有找到对应的成交"},
        {TAPIERROR_LOCALMODIFY_ACCOUNT, "订单修改时客户账号变动"},
        {TAPIERROR_LOCALTRANSFER_ACCOUNT, "订单转移时客户账号没有变动"},
        {TAPIERROR_INPUTERROR_NULL, "输入数据为NULL"},
        {TAPIERROR_INPUTERROR_TAPIYNFLAG, "输入错误的:TAPIYNFLAG"},
        {TAPIERROR_INPUTERROR_TAPILOGLEVEL, "输入错误的:TAPILOGLEVEL"},
        {TAPIERROR_INPUTERROR_TAPICommodityType, "输入错误的:TAPICommodityType"},
        {TAPIERROR_INPUTERROR_TAPICallOrPutFlagType, "输入错误的:TAPICallOrPutFlagType"},
        {TAPIERROR_INPUTERROR_TAPIBucketDateFlag, "输入错误的:TAPIBucketDateFlag"},
        {TAPIERROR_INPUTERROR_TAPIHisQuoteType, "输入错误的:TAPIHisQuoteType"},
        {TAPIERROR_INPUTERROR_TAPIAccountType, "输入错误的:TAPIAccountType"},
        {TAPIERROR_INPUTERROR_TAPIUserTypeType, "输入错误的:TAPIUserTypeType"},
        {TAPIERROR_INPUTERROR_TAPIAccountState, "输入错误的:TAPIAccountState"},
        {TAPIERROR_INPUTERROR_TAPIAccountFamilyType, "输入错误的:TAPIAccountFamilyType"},
        {TAPIERROR_INPUTERROR_TAPIOrderTypeType, "输入错误的:TAPIOrderTypeType"},
        {TAPIERROR_INPUTERROR_TAPIOrderSourceType, "输入错误的:TAPIOrderSourceType"},
        {TAPIERROR_INPUTERROR_TAPITimeInForceType, "输入错误的:TAPITimeInForceType"},
        {TAPIERROR_INPUTERROR_TAPISideType, "输入错误的:TAPISideType"},
        {TAPIERROR_INPUTERROR_TAPIPositionEffectType, "输入错误的:TAPIPositionEffectType"},
        {TAPIERROR_INPUTERROR_TAPIHedgeFlagType, "输入错误的:TAPIHedgeFlagType"},
        {TAPIERROR_INPUTERROR_TAPIOrderStateType, "输入错误的:TAPIOrderStateType"},
        {TAPIERROR_INPUTERROR_TAPICalculateModeType, "输入错误的:TAPICalculateModeType"},
        {TAPIERROR_INPUTERROR_TAPIMatchSourceType, "输入错误的:TAPIMatchSourceType"},
        {TAPIERROR_INPUTERROR_TAPIOpenCloseModeType, "输入错误的:TAPIOpenCloseModeType"},
        {TAPIERROR_INPUTERROR_TAPIFutureAlgType, "输入错误的:TAPIFutureAlgType"},
        {TAPIERROR_INPUTERROR_TAPIOptionAlgType, "输入错误的:TAPIOptionAlgType"},
        {TAPIERROR_INPUTERROR_TAPIBankAccountLWFlagType, "输入错误的:TAPIBankAccountLWFlagType"},
        {TAPIERROR_INPUTERROR_TAPIBankAccountStateType, "输入错误的:TAPIBankAccountStateType"},
        {TAPIERROR_INPUTERROR_TAPIBankAccountSwapStateType, "输入错误的:TAPIBankAccountSwapStateType"},
        {TAPIERROR_INPUTERROR_TAPIBankAccountTransferStateType, "输入错误的:TAPIBankAccountTransferStateType"},
        {TAPIERROR_INPUTERROR_TAPIMarginCalculateModeType, "输入错误的:TAPIMarginCalculateModeType"},
        {TAPIERROR_INPUTERROR_TAPIOptionMarginCalculateModeType, "输入错误的:TAPIOptionMarginCalculateModeType"},
        {TAPIERROR_INPUTERROR_TAPICmbDirectType, "输入错误的:TAPICmbDirectType"},
        {TAPIERROR_INPUTERROR_TAPIDeliveryModeType, "输入错误的:TAPIDeliveryModeType"},
        {TAPIERROR_INPUTERROR_TAPIContractTypeType, "输入错误的:TAPIContractTypeType"},
        {TAPIERROR_INPUTERROR_TAPIPartyTypeType, "输入错误的:TAPIPartyTypeType"},
        {TAPIERROR_INPUTERROR_TAPIPartyCertificateTypeType, "输入错误的:TAPIPartyCertificateTypeType"},
        {TAPIERROR_INPUTERROR_TAPIMsgReceiverType, "输入错误的:TAPIMsgReceiverType"},
        {TAPIERROR_INPUTERROR_TAPIMsgTypeType, "输入错误的:TAPIMsgTypeType"},
        {TAPIERROR_INPUTERROR_TAPIMsgLevelType, "输入错误的:TAPIMsgLevelType"},
        {TAPIERROR_INPUTERROR_TAPITransferDirectType, "输入错误的:TAPITransferDirectType"},
        {TAPIERROR_INPUTERROR_TAPITransferStateType, "输入错误的:TAPITransferStateType"},
        {TAPIERROR_INPUTERROR_TAPITransferTypeType, "输入错误的:TAPITransferTypeType"},
        {TAPIERROR_INPUTERROR_TAPITransferDeviceIDType, "输入错误的:TAPITransferDeviceIDType"},
        {TAPIERROR_INPUTERROR_TAPITacticsTypeType, "输入错误的:TAPITacticsTypeType"},
        {TAPIERROR_INPUTERROR_TAPIORDERACT, "输入错误的:TAPIORDERACT"},
        {TAPIERROR_INPUTERROR_TAPIBillTypeType, "输入错误的:TAPIBillTypeType"},
        {TAPIERROR_INPUTERROR_TAPIBillFileTypeType, "输入错误的:TAPIBillFileTypeType"},
        {TAPIERROR_INPUTERROR_TAPIOFFFlagType, "输入错误的:TAPIOFFFlagType"},
        {TAPIERROR_INPUTERROR_TAPICashAdjustTypeType, "输入错误的:TAPICashAdjustTypeType"},
        {TAPIERROR_INPUTERROR_TAPITriggerConditionType, "输入错误的:TAPITriggerConditionType"},
        {TAPIERROR_INPUTERROR_TAPITriggerPriceTypeType, "输入错误的:TAPITriggerPriceTypeType"},
        {TAPIERROR_INPUTERROR_TAPITradingStateType, "输入错误的:TAPITradingStateType"},
        {TAPIERROR_INPUTERROR_TAPIMarketLevelType, "输入错误的:TAPIMarketLevelType"},
        {TAPIERROR_INPUTERROR_TAPIOrderQryTypeType, "输入错误的:TAPIOrderQryTypeType"},
        {TAPIERROR_INPUTERROR_TAPIClientID, "输入错误的: ClientID，ClientID包含特殊字符。"},
        {TAPIERROR_INPUTERROR_QryHisQuoteParam, "历史行情查询参数不合法"},
        {TAPIERROR_INPUTERROR_TAPIIncludeNAN, "价格和数量中包含NAN或者INF不合法的数值"},
        {TAPIERROR_DISCONNECT_CLOSE_INIT, "主动断开"},
        {TAPIERROR_DISCONNECT_CLOSE_PASS, "被动断开"},
        {TAPIERROR_DISCONNECT_READ_ERROR, "读错误"},
        {TAPIERROR_DISCONNECT_WRITE_ERROR, "写错误"},
        {TAPIERROR_DISCONNECT_BUF_FULL, "缓冲区满"},
        {TAPIERROR_DISCONNECT_IOCP_ERROR, "异步操作错误"},
        {TAPIERROR_DISCONNECT_PARSE_ERROR, "解析数据错误"},
        {TAPIERROR_DISCONNECT_CONNECT_TIMEOUT, "连接超时"},
        {TAPIERROR_DISCONNECT_INIT_ERROR, "初始化失败"},
        {TAPIERROR_DISCONNECT_HAS_CONNECTED, "已经连接"},
        {TAPIERROR_DISCONNECT_HAS_EXIT, "工作线程已结束"},
        {TAPIERROR_DISCONNECT_TRY_LATER, "操作正在进行，请稍后重试"}
};

const std::string es9ErrorMsg(const ITapTrade::TAPIINT32& errorCode) {
    auto it = MAPPING.find(errorCode);
    if (it != MAPPING.end()) {
        return it->second;
    }
    return "未知调用错误" + boost::lexical_cast<std::string>(errorCode);
}


} // end namespace framework
} // end namespace es9ext
