/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.trade.hosting.history.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class QueryTimePeriod implements org.apache.thrift.TBase<QueryTimePeriod, QueryTimePeriod._Fields>, java.io.Serializable, Cloneable, Comparable<QueryTimePeriod> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("QueryTimePeriod");

  private static final org.apache.thrift.protocol.TField START_TIMESTAMP_MS_FIELD_DESC = new org.apache.thrift.protocol.TField("startTimestampMs", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField END_TIMESTAMP_MS_FIELD_DESC = new org.apache.thrift.protocol.TField("endTimestampMs", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new QueryTimePeriodStandardSchemeFactory());
    schemes.put(TupleScheme.class, new QueryTimePeriodTupleSchemeFactory());
  }

  public long startTimestampMs; // optional
  public long endTimestampMs; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    START_TIMESTAMP_MS((short)1, "startTimestampMs"),
    END_TIMESTAMP_MS((short)2, "endTimestampMs");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // START_TIMESTAMP_MS
          return START_TIMESTAMP_MS;
        case 2: // END_TIMESTAMP_MS
          return END_TIMESTAMP_MS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STARTTIMESTAMPMS_ISSET_ID = 0;
  private static final int __ENDTIMESTAMPMS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.START_TIMESTAMP_MS,_Fields.END_TIMESTAMP_MS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.START_TIMESTAMP_MS, new org.apache.thrift.meta_data.FieldMetaData("startTimestampMs", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.END_TIMESTAMP_MS, new org.apache.thrift.meta_data.FieldMetaData("endTimestampMs", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(QueryTimePeriod.class, metaDataMap);
  }

  public QueryTimePeriod() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public QueryTimePeriod(QueryTimePeriod other) {
    __isset_bitfield = other.__isset_bitfield;
    this.startTimestampMs = other.startTimestampMs;
    this.endTimestampMs = other.endTimestampMs;
  }

  public QueryTimePeriod deepCopy() {
    return new QueryTimePeriod(this);
  }

  @Override
  public void clear() {
    setStartTimestampMsIsSet(false);
    this.startTimestampMs = 0;
    setEndTimestampMsIsSet(false);
    this.endTimestampMs = 0;
  }

  public long getStartTimestampMs() {
    return this.startTimestampMs;
  }

  public QueryTimePeriod setStartTimestampMs(long startTimestampMs) {
    this.startTimestampMs = startTimestampMs;
    setStartTimestampMsIsSet(true);
    return this;
  }

  public void unsetStartTimestampMs() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STARTTIMESTAMPMS_ISSET_ID);
  }

  /** Returns true if field startTimestampMs is set (has been assigned a value) and false otherwise */
  public boolean isSetStartTimestampMs() {
    return EncodingUtils.testBit(__isset_bitfield, __STARTTIMESTAMPMS_ISSET_ID);
  }

  public void setStartTimestampMsIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STARTTIMESTAMPMS_ISSET_ID, value);
  }

  public long getEndTimestampMs() {
    return this.endTimestampMs;
  }

  public QueryTimePeriod setEndTimestampMs(long endTimestampMs) {
    this.endTimestampMs = endTimestampMs;
    setEndTimestampMsIsSet(true);
    return this;
  }

  public void unsetEndTimestampMs() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ENDTIMESTAMPMS_ISSET_ID);
  }

  /** Returns true if field endTimestampMs is set (has been assigned a value) and false otherwise */
  public boolean isSetEndTimestampMs() {
    return EncodingUtils.testBit(__isset_bitfield, __ENDTIMESTAMPMS_ISSET_ID);
  }

  public void setEndTimestampMsIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ENDTIMESTAMPMS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case START_TIMESTAMP_MS:
      if (value == null) {
        unsetStartTimestampMs();
      } else {
        setStartTimestampMs((Long)value);
      }
      break;

    case END_TIMESTAMP_MS:
      if (value == null) {
        unsetEndTimestampMs();
      } else {
        setEndTimestampMs((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case START_TIMESTAMP_MS:
      return Long.valueOf(getStartTimestampMs());

    case END_TIMESTAMP_MS:
      return Long.valueOf(getEndTimestampMs());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case START_TIMESTAMP_MS:
      return isSetStartTimestampMs();
    case END_TIMESTAMP_MS:
      return isSetEndTimestampMs();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof QueryTimePeriod)
      return this.equals((QueryTimePeriod)that);
    return false;
  }

  public boolean equals(QueryTimePeriod that) {
    if (that == null)
      return false;

    boolean this_present_startTimestampMs = true && this.isSetStartTimestampMs();
    boolean that_present_startTimestampMs = true && that.isSetStartTimestampMs();
    if (this_present_startTimestampMs || that_present_startTimestampMs) {
      if (!(this_present_startTimestampMs && that_present_startTimestampMs))
        return false;
      if (this.startTimestampMs != that.startTimestampMs)
        return false;
    }

    boolean this_present_endTimestampMs = true && this.isSetEndTimestampMs();
    boolean that_present_endTimestampMs = true && that.isSetEndTimestampMs();
    if (this_present_endTimestampMs || that_present_endTimestampMs) {
      if (!(this_present_endTimestampMs && that_present_endTimestampMs))
        return false;
      if (this.endTimestampMs != that.endTimestampMs)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(QueryTimePeriod other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStartTimestampMs()).compareTo(other.isSetStartTimestampMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartTimestampMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startTimestampMs, other.startTimestampMs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEndTimestampMs()).compareTo(other.isSetEndTimestampMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndTimestampMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endTimestampMs, other.endTimestampMs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("QueryTimePeriod(");
    boolean first = true;

    if (isSetStartTimestampMs()) {
      sb.append("startTimestampMs:");
      sb.append(this.startTimestampMs);
      first = false;
    }
    if (isSetEndTimestampMs()) {
      if (!first) sb.append(", ");
      sb.append("endTimestampMs:");
      sb.append(this.endTimestampMs);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class QueryTimePeriodStandardSchemeFactory implements SchemeFactory {
    public QueryTimePeriodStandardScheme getScheme() {
      return new QueryTimePeriodStandardScheme();
    }
  }

  private static class QueryTimePeriodStandardScheme extends StandardScheme<QueryTimePeriod> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, QueryTimePeriod struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // START_TIMESTAMP_MS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startTimestampMs = iprot.readI64();
              struct.setStartTimestampMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // END_TIMESTAMP_MS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endTimestampMs = iprot.readI64();
              struct.setEndTimestampMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, QueryTimePeriod struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetStartTimestampMs()) {
        oprot.writeFieldBegin(START_TIMESTAMP_MS_FIELD_DESC);
        oprot.writeI64(struct.startTimestampMs);
        oprot.writeFieldEnd();
      }
      if (struct.isSetEndTimestampMs()) {
        oprot.writeFieldBegin(END_TIMESTAMP_MS_FIELD_DESC);
        oprot.writeI64(struct.endTimestampMs);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class QueryTimePeriodTupleSchemeFactory implements SchemeFactory {
    public QueryTimePeriodTupleScheme getScheme() {
      return new QueryTimePeriodTupleScheme();
    }
  }

  private static class QueryTimePeriodTupleScheme extends TupleScheme<QueryTimePeriod> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, QueryTimePeriod struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetStartTimestampMs()) {
        optionals.set(0);
      }
      if (struct.isSetEndTimestampMs()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetStartTimestampMs()) {
        oprot.writeI64(struct.startTimestampMs);
      }
      if (struct.isSetEndTimestampMs()) {
        oprot.writeI64(struct.endTimestampMs);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, QueryTimePeriod struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.startTimestampMs = iprot.readI64();
        struct.setStartTimestampMsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.endTimestampMs = iprot.readI64();
        struct.setEndTimestampMsIsSet(true);
      }
    }
  }

}

