/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.trade.hosting.arbitrage.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum HostingXQComposeLimitOrderFirstLegChooseMode implements org.apache.thrift.TEnum {
  FIRST_LEG_CHOOSE_MODE_DEFAULT(0),
  FIRST_LEG_CHOOSE_MODE_APPOINT(1),
  FIRST_LEG_CHOOSE_MODE_OUTER_DISC(2);

  private final int value;

  private HostingXQComposeLimitOrderFirstLegChooseMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static HostingXQComposeLimitOrderFirstLegChooseMode findByValue(int value) { 
    switch (value) {
      case 0:
        return FIRST_LEG_CHOOSE_MODE_DEFAULT;
      case 1:
        return FIRST_LEG_CHOOSE_MODE_APPOINT;
      case 2:
        return FIRST_LEG_CHOOSE_MODE_OUTER_DISC;
      default:
        return null;
    }
  }
}
